// Copyright (c) 2024 ByoriDB
//
// This source code is licensed under Apache 2.0 License.

//! Authentication and authorization for ByoriDB
//!
//! This module provides:
//! - User authentication
//! - Role-based access control (RBAC)
//! - Permission management
//! - Space-level access control

use super::error::{GraphError, Result};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, VecDeque};
use std::net::IpAddr;
use std::sync::Arc;
use std::time::{Duration, Instant, SystemTime};
use tokio::sync::{Mutex, RwLock, Semaphore};

/// Default session TTL: 24 hours
pub const DEFAULT_SESSION_TTL_SECS: u64 = 24 * 60 * 60;

/// Environment variable that sets the root user's password at startup.
/// If unset or blank, embedded callers receive a cryptographically random
/// password that is deliberately never written to logs. The standalone server
/// requires a non-blank value and fails fast before constructing the
/// authentication manager.
pub const ROOT_PASSWORD_ENV: &str = "BYORIDB_ROOT_PASSWORD";

/// Maximum consecutive failed login attempts before lockout.
pub const MAX_FAILED_ATTEMPTS: u32 = 5;
/// Lockout duration after exceeding MAX_FAILED_ATTEMPTS.
pub const LOCKOUT_DURATION_SECS: u64 = 300; // 5 minutes
const MAX_CONCURRENT_ARGON2_VERIFICATIONS: usize = 4;
const LOGIN_RATE_WINDOW: Duration = Duration::from_secs(60);
const MAX_ACCOUNT_ATTEMPTS_PER_WINDOW: usize = 20;
const MAX_SOURCE_ATTEMPTS_PER_WINDOW: usize = 60;
const MAX_RATE_LIMIT_KEYS: usize = 10_000;

/// Verification honors cost parameters embedded in a PHC string. Accept only
/// a narrow envelope around the profile generated by this release so a
/// corrupted record cannot install either a cheap hash or a login-time DoS.
const MIN_PERSISTED_ARGON2_M_COST_KIB: u32 = argon2::Params::DEFAULT_M_COST;
const MAX_PERSISTED_ARGON2_M_COST_KIB: u32 = 64 * 1024;
const MIN_PERSISTED_ARGON2_T_COST: u32 = argon2::Params::DEFAULT_T_COST;
const MAX_PERSISTED_ARGON2_T_COST: u32 = 4;
const MAX_PERSISTED_ARGON2_P_COST: u32 = 4;

/// Structurally valid default-cost sentinel used only if the operating system
/// cannot provide entropy while building an infallible, fail-closed manager.
/// Its verification result is always discarded.
const FALLBACK_DUMMY_PASSWORD_HASH: &str = concat!(
    "$argon2id$v=19$m=19456,t=2,p=1$YnlvcmlkYi10aW1pbmc$",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
);

/// Per-username failed login tracking entry.
struct FailedAttempt {
    count: u32,
    locked_until: Option<SystemTime>,
}

#[derive(Default)]
struct LoginRateLimiter {
    attempts: Mutex<HashMap<String, VecDeque<Instant>>>,
}

impl LoginRateLimiter {
    async fn check_and_record(&self, username: &str, source: Option<IpAddr>) -> bool {
        let now = Instant::now();
        let cutoff = now.checked_sub(LOGIN_RATE_WINDOW).unwrap_or(now);
        let mut keys = vec![(
            format!("account:{}", username.trim().to_ascii_lowercase()),
            MAX_ACCOUNT_ATTEMPTS_PER_WINDOW,
        )];
        if let Some(source) = source {
            keys.push((format!("source:{source}"), MAX_SOURCE_ATTEMPTS_PER_WINDOW));
        }

        let mut attempts = self.attempts.lock().await;
        if attempts.len() >= MAX_RATE_LIMIT_KEYS {
            attempts.retain(|_, entries| entries.back().is_some_and(|entry| *entry >= cutoff));
        }
        let new_key_count = keys
            .iter()
            .filter(|(key, _)| !attempts.contains_key(key))
            .count();
        if attempts.len().saturating_add(new_key_count) > MAX_RATE_LIMIT_KEYS {
            return false;
        }

        for (key, limit) in &keys {
            if let Some(entries) = attempts.get_mut(key) {
                while entries.front().is_some_and(|entry| *entry < cutoff) {
                    entries.pop_front();
                }
                if entries.len() >= *limit {
                    return false;
                }
            }
        }
        for (key, _) in keys {
            attempts.entry(key).or_default().push_back(now);
        }
        true
    }
}

/// Authentication manager
pub struct AuthManager {
    users: Arc<RwLock<HashMap<String, User>>>,
    roles: Arc<RwLock<HashMap<String, Role>>>,
    sessions: Arc<RwLock<HashMap<i64, Session>>>,
    /// Valid Argon2 hash used to equalize authentication work for unknown or
    /// locked accounts without creating per-unknown-user state.
    dummy_password_hash: String,
    /// Brute-force protection: tracks consecutive failures per username.
    failed_attempts: Arc<RwLock<HashMap<String, FailedAttempt>>>,
    login_rate_limiter: Arc<LoginRateLimiter>,
    argon2_verification_limit: Arc<Semaphore>,
    session_ttl: Duration,
}

impl AuthManager {
    pub fn new() -> Self {
        Self::with_ttl(Duration::from_secs(DEFAULT_SESSION_TTL_SECS))
    }

    /// Construct with a custom session TTL. Root password is resolved from
    /// [`ROOT_PASSWORD_ENV`] or a randomly generated value. Blank environment
    /// values are treated as unset.
    pub fn with_ttl(session_ttl: Duration) -> Self {
        // Determine root password:
        //   1. BYORIDB_ROOT_PASSWORD env var (explicit, preferred for production)
        //   2. Cryptographically random password (never logged)
        let (root_password, generated) = match std::env::var(ROOT_PASSWORD_ENV) {
            Ok(p) if !p.trim().is_empty() => (p, false),
            _ => match Self::generate_random_password() {
                Ok(password) => (password, true),
                Err(error) => {
                    tracing::error!(err = %error, "Failed to generate an ephemeral root credential");
                    return Self::fail_closed(session_ttl);
                }
            },
        };

        if generated {
            tracing::warn!(
                "No {} env var set; generated an ephemeral root credential that is not logged. \
                Set {} before starting a network server.",
                ROOT_PASSWORD_ENV,
                ROOT_PASSWORD_ENV
            );
        } else {
            tracing::info!("Using root password from {} env var", ROOT_PASSWORD_ENV);
        }

        Self::with_config(&root_password, session_ttl)
    }

    /// Construct with an explicit root password and session TTL.
    ///
    /// Compatibility constructor for embedded callers that must receive a
    /// manager directly. It fails closed if credential initialization fails.
    /// Network launchers should use [`Self::try_with_config`] so startup errors
    /// are returned to the caller.
    pub fn with_config(root_password: &str, session_ttl: Duration) -> Self {
        match Self::try_with_config(root_password, session_ttl) {
            Ok(manager) => manager,
            Err(error) => {
                tracing::error!(err = %error, "Authentication manager initialization failed closed");
                Self::fail_closed(session_ttl)
            }
        }
    }

    /// Construct with an explicit root password and return initialization
    /// failures to the caller. Blank credentials are rejected rather than
    /// silently changing the configured password.
    pub fn try_with_config(root_password: &str, session_ttl: Duration) -> Result<Self> {
        let root_hash = Self::hash_password(root_password)?;
        // Generate the timing sentinel at startup and immediately discard its
        // plaintext. A source-known sentinel could be supplied deliberately,
        // turning the dummy verification into its success path.
        let dummy_password = Self::generate_random_password()?;
        let dummy_password_hash = Self::hash_password(&dummy_password)?;

        Ok(Self::from_password_hashes(
            Some(root_hash),
            dummy_password_hash,
            session_ttl,
        ))
    }

    /// Build a manager with no authenticating root identity. This is used only
    /// by the infallible compatibility constructor after an initialization
    /// error; the bootstrap identity remains unavailable rather than panicking
    /// or accepting an unintended credential.
    fn fail_closed(session_ttl: Duration) -> Self {
        let dummy_password_hash = match Self::generate_random_password()
            .and_then(|password| Self::hash_password(&password))
        {
            Ok(hash) => hash,
            Err(error) => {
                tracing::error!(err = %error, "Failed to initialize authentication timing sentinel");
                FALLBACK_DUMMY_PASSWORD_HASH.to_string()
            }
        };

        Self::from_password_hashes(None, dummy_password_hash, session_ttl)
    }

    fn from_password_hashes(
        root_hash: Option<String>,
        dummy_password_hash: String,
        session_ttl: Duration,
    ) -> Self {
        let mut users = HashMap::new();
        if let Some(root_hash) = root_hash {
            let root = User {
                username: "root".to_string(),
                password_hash: root_hash,
                roles: vec!["GOD".to_string()],
                enabled: true,
            };
            users.insert("root".to_string(), root);
        }

        let mut roles = HashMap::new();

        // Create default roles
        roles.insert("GOD".to_string(), Role::god());
        roles.insert("ADMIN".to_string(), Role::admin());
        roles.insert("DBA".to_string(), Role::dba());
        roles.insert("USER".to_string(), Role::user());
        roles.insert("GUEST".to_string(), Role::guest());

        AuthManager {
            users: Arc::new(RwLock::new(users)),
            roles: Arc::new(RwLock::new(roles)),
            sessions: Arc::new(RwLock::new(HashMap::new())),
            dummy_password_hash,
            failed_attempts: Arc::new(RwLock::new(HashMap::new())),
            login_rate_limiter: Arc::new(LoginRateLimiter::default()),
            argon2_verification_limit: Arc::new(Semaphore::new(
                MAX_CONCURRENT_ARGON2_VERIFICATIONS,
            )),
            session_ttl,
        }
    }

    /// Generate a cryptographically secure random password (24 bytes, hex-encoded → 48 chars).
    fn generate_random_password() -> Result<String> {
        use argon2::password_hash::rand_core::{OsRng, RngCore};
        let mut bytes = [0u8; 24];
        OsRng.try_fill_bytes(&mut bytes).map_err(|error| {
            GraphError::InternalError(format!("Credential generation failed: {error}"))
        })?;
        Ok(bytes.iter().map(|b| format!("{:02x}", b)).collect())
    }

    /// Authenticate a user
    pub async fn authenticate(&self, username: &str, password: &str) -> Result<i64> {
        self.authenticate_from(username, password, None).await
    }

    /// Authenticate a user while applying both account and network-source load
    /// controls. Protocol servers should pass the peer IP; embedded callers can
    /// continue using [`Self::authenticate`].
    pub async fn authenticate_from(
        &self,
        username: &str,
        password: &str,
        source: Option<IpAddr>,
    ) -> Result<i64> {
        if !self
            .login_rate_limiter
            .check_and_record(username, source)
            .await
        {
            return Err(GraphError::AuthFailed(
                "Too many authentication attempts".to_string(),
            ));
        }
        if username.trim().is_empty() || password.trim().is_empty() {
            // Preserve comparable Argon2 work for invalid blank credentials.
            let _ = self
                .verify_password_bounded(password, &self.dummy_password_hash)
                .await?;
            return Err(GraphError::AuthFailed("Invalid credentials".to_string()));
        }

        // Brute-force check: reject if account is locked
        let account_locked = {
            let attempts = self.failed_attempts.read().await;
            attempts
                .get(username)
                .and_then(|entry| entry.locked_until)
                .is_some_and(|locked_until| SystemTime::now() < locked_until)
        };
        if account_locked {
            // Keep locked-account responses computationally comparable to a
            // normal password attempt. Do not reveal this state at transports.
            let _ = self
                .verify_password_bounded(password, &self.dummy_password_hash)
                .await?;
            return Err(GraphError::AuthFailed(
                "Account locked due to too many failed attempts. Try again later.".to_string(),
            ));
        }

        let user = self.users.read().await.get(username).cloned();
        let Some(user) = user else {
            // Unknown usernames still pay one Argon2 verification, preventing a
            // cheap timing oracle. They are intentionally not added to
            // `failed_attempts`, which would permit unbounded memory growth.
            let _ = self
                .verify_password_bounded(password, &self.dummy_password_hash)
                .await?;
            return Err(GraphError::AuthFailed("User not found".to_string()));
        };

        // Always perform the expensive verification before reporting disabled
        // state so all credential failures have comparable work.
        let password_valid = self
            .verify_password_bounded(password, &user.password_hash)
            .await?;
        if !user.enabled {
            return Err(GraphError::AuthFailed("User is disabled".to_string()));
        }

        if !password_valid {
            // Record failure
            let mut attempts = self.failed_attempts.write().await;
            let entry = attempts
                .entry(username.to_string())
                .or_insert(FailedAttempt {
                    count: 0,
                    locked_until: None,
                });
            entry.count += 1;
            if entry.count >= MAX_FAILED_ATTEMPTS {
                entry.locked_until =
                    Some(SystemTime::now() + Duration::from_secs(LOCKOUT_DURATION_SECS));
                tracing::warn!(
                    failed_attempts = entry.count,
                    "Account locked after repeated authentication failures"
                );
            }
            return Err(GraphError::AuthFailed("Invalid password".to_string()));
        }

        let now = SystemTime::now();
        let mut sessions = self.sessions.write().await;
        // Cryptographically random 63-bit bearer token. Clear the sign bit
        // instead of calling `i64::abs`, which overflows for `i64::MIN`, and
        // retry the vanishingly unlikely collision rather than replacing an
        // existing session.
        let session_id = loop {
            use argon2::password_hash::rand_core::{OsRng, RngCore};
            let mut random_bytes = [0u8; 8];
            OsRng.try_fill_bytes(&mut random_bytes).map_err(|error| {
                GraphError::InternalError(format!("Session ID generation failed: {error}"))
            })?;
            let candidate = (u64::from_le_bytes(random_bytes) >> 1) as i64;
            if candidate != 0 && !sessions.contains_key(&candidate) {
                break candidate;
            }
        };
        // No fallible work remains after a non-colliding bearer is selected.
        // Clear the credential-failure counter only once session creation can
        // complete without a partial success state.
        self.failed_attempts.write().await.remove(username);
        let session = Session {
            id: session_id,
            username: username.to_string(),
            roles: user.roles.clone(),
            created_at: now,
            expires_at: now + self.session_ttl,
        };
        sessions.insert(session_id, session);
        tracing::info!("User authenticated");

        Ok(session_id)
    }

    async fn verify_password_bounded(&self, password: &str, hash: &str) -> Result<bool> {
        let permit = self
            .argon2_verification_limit
            .clone()
            .acquire_owned()
            .await
            .map_err(|_| GraphError::InternalError("Authentication worker closed".to_string()))?;
        let password = password.to_string();
        let hash = hash.to_string();
        tokio::task::spawn_blocking(move || {
            let _permit = permit;
            Self::verify_password(&password, &hash)
        })
        .await
        .map_err(|error| {
            GraphError::InternalError(format!("Authentication worker failed: {error}"))
        })
    }

    /// Create a new user
    pub async fn create_user(
        &self,
        username: &str,
        password: &str,
        roles: Vec<String>,
    ) -> Result<()> {
        if username.trim().is_empty() {
            return Err(GraphError::InvalidOperation(
                "Username must not be blank".to_string(),
            ));
        }
        if username.eq_ignore_ascii_case("root") {
            return Err(GraphError::InvalidOperation(
                "The root identity is reserved".to_string(),
            ));
        }
        if roles.iter().any(|role| role.eq_ignore_ascii_case("GOD")) {
            return Err(GraphError::InvalidOperation(
                "The root-only role cannot be assigned".to_string(),
            ));
        }
        let mut users = self.users.write().await;

        if users.contains_key(username) {
            return Err(GraphError::InvalidOperation(format!(
                "User {} already exists",
                username
            )));
        }

        let user = User {
            username: username.to_string(),
            password_hash: Self::hash_password(password)?,
            roles,
            enabled: true,
        };

        users.insert(username.to_string(), user);
        drop(users);

        tracing::info!("User created");

        Ok(())
    }

    /// Delete a user
    pub async fn delete_user(&self, username: &str) -> Result<()> {
        let mut users = self.users.write().await;

        if username.eq_ignore_ascii_case("root") {
            return Err(GraphError::InvalidOperation(
                "Cannot delete root user".to_string(),
            ));
        }

        users
            .remove(username)
            .ok_or_else(|| GraphError::InvalidOperation(format!("User {} not found", username)))?;
        drop(users);

        self.invalidate_user_sessions(username).await;

        tracing::info!("User deleted");

        Ok(())
    }

    /// Grant a role to a user
    pub async fn grant_role(&self, username: &str, role: &str) -> Result<()> {
        if username.eq_ignore_ascii_case("root") {
            return Err(GraphError::InvalidOperation(
                "Cannot alter root user roles".to_string(),
            ));
        }
        if role.eq_ignore_ascii_case("GOD") {
            return Err(GraphError::InvalidOperation(
                "The root-only role cannot be assigned".to_string(),
            ));
        }
        let mut users = self.users.write().await;

        let user = users
            .get_mut(username)
            .ok_or_else(|| GraphError::InvalidOperation(format!("User {} not found", username)))?;

        if !user.roles.contains(&role.to_string()) {
            user.roles.push(role.to_string());
        }
        drop(users);

        self.invalidate_user_sessions(username).await;

        tracing::info!("Role granted to user");

        Ok(())
    }

    /// Revoke a role from a user
    pub async fn revoke_role(&self, username: &str, role: &str) -> Result<()> {
        if username.eq_ignore_ascii_case("root") {
            return Err(GraphError::InvalidOperation(
                "Cannot alter root user roles".to_string(),
            ));
        }
        let mut users = self.users.write().await;

        let user = users
            .get_mut(username)
            .ok_or_else(|| GraphError::InvalidOperation(format!("User {} not found", username)))?;

        user.roles.retain(|r| r != role);
        drop(users);

        self.invalidate_user_sessions(username).await;

        tracing::info!("Role revoked from user");

        Ok(())
    }

    /// Enable or disable a user. Disabled users cannot authenticate.
    /// The root user cannot be disabled.
    pub async fn set_user_enabled(&self, username: &str, enabled: bool) -> Result<()> {
        if username.eq_ignore_ascii_case("root") {
            return Err(GraphError::InvalidOperation(
                "Cannot alter root user state".to_string(),
            ));
        }

        let mut users = self.users.write().await;
        let user = users
            .get_mut(username)
            .ok_or_else(|| GraphError::InvalidOperation(format!("User {} not found", username)))?;

        user.enabled = enabled;
        drop(users);

        // Authentication state is captured in bearer sessions. Revoke existing
        // sessions whenever account state changes so disable takes effect now.
        self.invalidate_user_sessions(username).await;

        tracing::info!(enabled = enabled, "User enabled state changed");

        Ok(())
    }

    /// Check if a session has permission
    pub async fn check_permission(
        &self,
        session_id: i64,
        space: &str,
        permission: Permission,
    ) -> Result<bool> {
        let session_roles = self
            .get_session_roles(session_id)
            .await
            .ok_or_else(|| GraphError::AuthFailed("Invalid or expired session".to_string()))?;

        let roles = self.roles.read().await;

        // Check if any role has the required permission
        for role_name in &session_roles {
            if let Some(role) = roles.get(role_name) {
                if role.has_permission(space, permission) {
                    return Ok(true);
                }
            }
        }

        Ok(false)
    }

    /// Get the roles associated with a session (for RBAC propagation to executor).
    /// Successful access refreshes the session's sliding TTL.
    pub async fn get_session_roles(&self, session_id: i64) -> Option<Vec<String>> {
        let now = SystemTime::now();
        let mut sessions = self.sessions.write().await;
        match sessions.get_mut(&session_id) {
            Some(session) if now < session.expires_at => {
                session.expires_at = now + self.session_ttl;
                Some(session.roles.clone())
            }
            Some(_) => {
                sessions.remove(&session_id);
                None
            }
            None => None,
        }
    }

    /// Check liveness without refreshing the sliding TTL. Background
    /// reconciliation uses this so maintenance itself cannot keep sessions
    /// alive forever.
    pub async fn has_live_session_without_touch(&self, session_id: i64) -> bool {
        let now = SystemTime::now();
        let mut sessions = self.sessions.write().await;
        match sessions.get(&session_id) {
            Some(session) if now < session.expires_at => true,
            Some(_) => {
                sessions.remove(&session_id);
                false
            }
            None => false,
        }
    }

    /// Whether a live bearer session belongs to a GOD/ADMIN principal.
    /// Missing and expired sessions are authentication failures; a valid
    /// non-admin session returns `Ok(false)` so HTTP can distinguish 401/403.
    pub async fn is_admin_session(&self, session_id: i64) -> Result<bool> {
        let roles = self
            .get_session_roles(session_id)
            .await
            .ok_or_else(|| GraphError::AuthFailed("Invalid or expired session".to_string()))?;
        Ok(roles.iter().any(|role| role == "GOD" || role == "ADMIN"))
    }

    /// Replace a user from the persisted KV representation. Root is owned by
    /// the process bootstrap credential and is never overridden by storage.
    /// Existing sessions are revoked when authentication or role state changes.
    pub async fn upsert_persisted_user(&self, user: User) -> Result<bool> {
        if user.username.eq_ignore_ascii_case("root") {
            return Ok(false);
        }
        if user
            .roles
            .iter()
            .any(|role| role.eq_ignore_ascii_case("GOD"))
        {
            return Err(GraphError::InvalidOperation(
                "Persisted user record contains a root-only role".to_string(),
            ));
        }
        if user.username.trim().is_empty() || user.password_hash.is_empty() {
            return Err(GraphError::InvalidOperation(
                "Persisted user record is incomplete".to_string(),
            ));
        }
        if !Self::is_supported_password_hash(&user.password_hash) {
            return Err(GraphError::InvalidOperation(
                "Persisted user record contains an invalid password hash".to_string(),
            ));
        }
        {
            let known_roles = self.roles.read().await;
            if user
                .roles
                .iter()
                .any(|role| !known_roles.contains_key(role))
            {
                return Err(GraphError::InvalidOperation(
                    "Persisted user record contains an unknown role".to_string(),
                ));
            }
        }

        let changed = {
            let mut users = self.users.write().await;
            if users.get(&user.username) == Some(&user) {
                false
            } else {
                users.insert(user.username.clone(), user.clone());
                true
            }
        };
        if changed {
            self.invalidate_user_sessions(&user.username).await;
        }
        Ok(changed)
    }

    /// Change a user's password and revoke all of that user's bearer sessions.
    pub async fn change_password(&self, username: &str, password: &str) -> Result<()> {
        if username.eq_ignore_ascii_case("root") {
            return Err(GraphError::InvalidOperation(
                "Root password is managed by process configuration".to_string(),
            ));
        }
        let password_hash = Self::hash_password(password)?;
        let mut users = self.users.write().await;
        let user = users
            .get_mut(username)
            .ok_or_else(|| GraphError::InvalidOperation(format!("User {} not found", username)))?;
        user.password_hash = password_hash;
        drop(users);
        self.invalidate_user_sessions(username).await;
        tracing::info!("User password changed");
        Ok(())
    }

    /// Revoke every live bearer session owned by a user.
    pub async fn invalidate_user_sessions(&self, username: &str) -> usize {
        let mut sessions = self.sessions.write().await;
        let before = sessions.len();
        sessions.retain(|_, session| session.username != username);
        before - sessions.len()
    }

    /// Remove all expired sessions. Returns the number of sessions removed.
    pub async fn cleanup_expired_sessions(&self) -> usize {
        let now = SystemTime::now();
        let mut sessions = self.sessions.write().await;
        let expired: Vec<i64> = sessions
            .iter()
            .filter(|(_, s)| now >= s.expires_at)
            .map(|(id, _)| *id)
            .collect();

        let count = expired.len();
        for id in expired {
            sessions.remove(&id);
        }
        count
    }

    /// Sign out a session
    pub async fn sign_out(&self, session_id: i64) -> Result<()> {
        let mut sessions = self.sessions.write().await;
        sessions
            .remove(&session_id)
            .ok_or_else(|| GraphError::InvalidOperation("Session not found".to_string()))?;

        tracing::info!("Session signed out");

        Ok(())
    }

    /// Hash password using argon2 (delegates to byoridb_common::crypto)
    fn hash_password(password: &str) -> Result<String> {
        if password.trim().is_empty() {
            return Err(GraphError::InvalidOperation(
                "Password must not be blank".to_string(),
            ));
        }
        byoridb_common::crypto::hash_password(password)
            .map_err(|e| GraphError::InternalError(e.to_string()))
    }

    /// Verify password against stored hash (delegates to byoridb_common::crypto)
    fn verify_password(password: &str, hash: &str) -> bool {
        byoridb_common::crypto::verify_password(password, hash)
    }

    fn is_supported_password_hash(encoded: &str) -> bool {
        use argon2::password_hash::PasswordHash;
        use argon2::{Algorithm, Params, Version};

        let Ok(parsed) = PasswordHash::new(encoded) else {
            return false;
        };
        if !matches!(
            Algorithm::try_from(parsed.algorithm),
            Ok(Algorithm::Argon2id)
        ) || !matches!(
            parsed
                .version
                .and_then(|version| Version::try_from(version).ok()),
            Some(Version::V0x13)
        ) {
            return false;
        }

        let (Some(salt), Some(output)) = (parsed.salt, parsed.hash.as_ref()) else {
            return false;
        };
        let mut salt_bytes = [0u8; 64];
        let Ok(decoded_salt) = salt.decode_b64(&mut salt_bytes) else {
            return false;
        };
        if decoded_salt.len() < argon2::MIN_SALT_LEN {
            return false;
        }

        let Ok(params) = Params::try_from(&parsed) else {
            return false;
        };
        (MIN_PERSISTED_ARGON2_M_COST_KIB..=MAX_PERSISTED_ARGON2_M_COST_KIB)
            .contains(&params.m_cost())
            && (MIN_PERSISTED_ARGON2_T_COST..=MAX_PERSISTED_ARGON2_T_COST)
                .contains(&params.t_cost())
            && (1..=MAX_PERSISTED_ARGON2_P_COST).contains(&params.p_cost())
            && output.len() == Params::DEFAULT_OUTPUT_LEN
    }
}

/// User information
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct User {
    pub username: String,
    pub password_hash: String,
    pub roles: Vec<String>,
    pub enabled: bool,
}

/// Role with permissions
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Role {
    pub name: String,
    pub permissions: Vec<PermissionEntry>,
}

impl Role {
    /// Create GOD role (all permissions)
    pub fn god() -> Self {
        Role {
            name: "GOD".to_string(),
            permissions: vec![
                PermissionEntry::any(Permission::Read),
                PermissionEntry::any(Permission::Write),
                PermissionEntry::any(Permission::Create),
                PermissionEntry::any(Permission::Delete),
                PermissionEntry::any(Permission::Alter),
                PermissionEntry::any(Permission::Drop),
            ],
        }
    }

    /// Create ADMIN role (admin permissions)
    pub fn admin() -> Self {
        Role {
            name: "ADMIN".to_string(),
            permissions: vec![
                PermissionEntry::any(Permission::Read),
                PermissionEntry::any(Permission::Write),
                PermissionEntry::any(Permission::Create),
                PermissionEntry::any(Permission::Delete),
                PermissionEntry::any(Permission::Alter),
                PermissionEntry::any(Permission::Drop),
            ],
        }
    }

    /// Create DBA role (database administrator - no drop)
    pub fn dba() -> Self {
        Role {
            name: "DBA".to_string(),
            permissions: vec![
                PermissionEntry::any(Permission::Read),
                PermissionEntry::any(Permission::Write),
                PermissionEntry::any(Permission::Create),
                PermissionEntry::any(Permission::Alter),
            ],
        }
    }

    /// Create USER role (basic permissions)
    pub fn user() -> Self {
        Role {
            name: "USER".to_string(),
            permissions: vec![
                PermissionEntry::any(Permission::Read),
                PermissionEntry::any(Permission::Write),
            ],
        }
    }

    /// Create GUEST role (read-only)
    pub fn guest() -> Self {
        Role {
            name: "GUEST".to_string(),
            permissions: vec![PermissionEntry::any(Permission::Read)],
        }
    }

    /// Check if role has a specific permission
    pub fn has_permission(&self, space: &str, permission: Permission) -> bool {
        self.permissions
            .iter()
            .any(|p| (p.space == "*" || p.space == space) && p.permission == permission)
    }
}

/// Permission entry
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PermissionEntry {
    pub space: String,
    pub permission: Permission,
}

impl PermissionEntry {
    pub fn any(permission: Permission) -> Self {
        PermissionEntry {
            space: "*".to_string(),
            permission,
        }
    }

    pub fn space(space: &str, permission: Permission) -> Self {
        PermissionEntry {
            space: space.to_string(),
            permission,
        }
    }
}

/// Permission types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Permission {
    Read,
    Write,
    Create,
    Delete,
    Alter,
    Drop,
}

/// Session information
#[derive(Debug, Clone)]
pub struct Session {
    pub id: i64,
    pub username: String,
    pub roles: Vec<String>,
    pub created_at: SystemTime,
    pub expires_at: SystemTime,
}

impl Session {
    /// Returns true if the session has passed its expiration time.
    pub fn is_expired(&self) -> bool {
        SystemTime::now() >= self.expires_at
    }
}

impl Default for AuthManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_PW: &str = "test-password-xyz";

    fn make_manager() -> AuthManager {
        AuthManager::with_config(TEST_PW, Duration::from_secs(3600))
    }

    fn make_manager_with_ttl(ttl: Duration) -> AuthManager {
        AuthManager::with_config(TEST_PW, ttl)
    }

    #[tokio::test]
    async fn test_authenticate_root_success() {
        let mgr = make_manager();
        let session_id = mgr.authenticate("root", TEST_PW).await.unwrap();
        assert!(session_id >= 1);
    }

    #[tokio::test]
    async fn explicit_blank_root_password_fails_closed() {
        assert!(AuthManager::try_with_config(" \t\n", Duration::from_secs(3600)).is_err());

        let mgr = AuthManager::with_config(" \t\n", Duration::from_secs(3600));
        assert!(mgr.authenticate("root", " \t\n").await.is_err());

        let preserved =
            AuthManager::try_with_config(" configured-secret ", Duration::from_secs(3600)).unwrap();
        assert!(preserved
            .authenticate("root", " configured-secret ")
            .await
            .is_ok());
        assert!(preserved
            .authenticate("root", "configured-secret")
            .await
            .is_err());
    }

    #[tokio::test]
    async fn blank_user_passwords_are_rejected() {
        let mgr = make_manager();
        for username in ["", " \t"] {
            let create_error = mgr
                .create_user(username, "password", vec!["USER".to_string()])
                .await
                .unwrap_err();
            assert!(matches!(create_error, GraphError::InvalidOperation(_)));
        }
        let persisted_username_error = mgr
            .upsert_persisted_user(User {
                username: " \t".to_string(),
                password_hash: byoridb_common::crypto::hash_password("password").unwrap(),
                roles: vec!["USER".to_string()],
                enabled: true,
            })
            .await
            .unwrap_err();
        assert!(matches!(
            persisted_username_error,
            GraphError::InvalidOperation(_)
        ));
        let create_error = mgr
            .create_user("blank-user", "\t\n", vec!["USER".to_string()])
            .await
            .unwrap_err();
        assert!(matches!(create_error, GraphError::InvalidOperation(_)));

        mgr.create_user("alice", "old-password", vec!["USER".to_string()])
            .await
            .unwrap();
        let session = mgr.authenticate("alice", "old-password").await.unwrap();
        let change_error = mgr.change_password("alice", "  ").await.unwrap_err();
        assert!(matches!(change_error, GraphError::InvalidOperation(_)));
        assert!(mgr.get_session_roles(session).await.is_some());
        assert!(mgr.authenticate("alice", "old-password").await.is_ok());

        use argon2::password_hash::{rand_core::OsRng, PasswordHasher, SaltString};
        let legacy_blank_hash = argon2::Argon2::default()
            .hash_password(b"", &SaltString::generate(&mut OsRng))
            .unwrap()
            .to_string();
        mgr.upsert_persisted_user(User {
            username: "legacy-blank".to_string(),
            password_hash: legacy_blank_hash,
            roles: vec!["USER".to_string()],
            enabled: true,
        })
        .await
        .unwrap();
        assert!(mgr.authenticate("legacy-blank", "").await.is_err());
    }

    #[tokio::test]
    async fn test_authenticate_wrong_password_fails() {
        let mgr = make_manager();
        let err = mgr.authenticate("root", "wrong").await.unwrap_err();
        assert!(matches!(err, GraphError::AuthFailed(_)));
    }

    #[tokio::test]
    async fn account_login_rate_limit_applies_even_to_locked_accounts() {
        let mgr = make_manager();
        for _ in 0..MAX_ACCOUNT_ATTEMPTS_PER_WINDOW {
            assert!(mgr.authenticate("root", "wrong-password").await.is_err());
        }
        let error = mgr
            .authenticate("root", TEST_PW)
            .await
            .expect_err("rate limit must reject a correct password after the window is exhausted");
        assert!(
            matches!(error, GraphError::AuthFailed(message) if message == "Too many authentication attempts")
        );
    }

    #[tokio::test]
    async fn source_login_rate_limit_spans_distinct_accounts() {
        let mgr = make_manager();
        let source = Some("192.0.2.10".parse().unwrap());
        for index in 0..MAX_SOURCE_ATTEMPTS_PER_WINDOW {
            let username = format!("unknown-{index}");
            assert!(mgr
                .authenticate_from(&username, "wrong-password", source)
                .await
                .is_err());
        }
        let error = mgr
            .authenticate_from("root", TEST_PW, source)
            .await
            .expect_err("source limit must apply across usernames");
        assert!(
            matches!(error, GraphError::AuthFailed(message) if message == "Too many authentication attempts")
        );
    }

    #[tokio::test]
    async fn test_authenticate_unknown_user_fails() {
        let mgr = make_manager();
        let err = mgr.authenticate("ghost", TEST_PW).await.unwrap_err();
        assert!(matches!(err, GraphError::AuthFailed(_)));
        assert!(
            !mgr.failed_attempts.read().await.contains_key("ghost"),
            "unknown usernames must not grow the lockout map"
        );
    }

    #[tokio::test]
    async fn test_create_and_authenticate_user() {
        let mgr = make_manager();
        mgr.create_user("alice", "alice-pw", vec!["USER".to_string()])
            .await
            .unwrap();

        let session_id = mgr.authenticate("alice", "alice-pw").await.unwrap();
        assert!(session_id >= 1);
    }

    #[tokio::test]
    async fn test_create_duplicate_user_fails() {
        let mgr = make_manager();
        mgr.create_user("alice", "pw", vec!["USER".to_string()])
            .await
            .unwrap();
        let err = mgr
            .create_user("alice", "pw2", vec!["USER".to_string()])
            .await
            .unwrap_err();
        assert!(matches!(err, GraphError::InvalidOperation(_)));
    }

    #[tokio::test]
    async fn test_delete_user() {
        let mgr = make_manager();
        mgr.create_user("alice", "pw", vec!["USER".to_string()])
            .await
            .unwrap();
        mgr.delete_user("alice").await.unwrap();

        let err = mgr.authenticate("alice", "pw").await.unwrap_err();
        assert!(matches!(err, GraphError::AuthFailed(_)));
    }

    #[tokio::test]
    async fn test_cannot_delete_root_user() {
        let mgr = make_manager();
        let err = mgr.delete_user("root").await.unwrap_err();
        assert!(matches!(err, GraphError::InvalidOperation(_)));
    }

    #[tokio::test]
    async fn test_grant_and_revoke_role() {
        let mgr = make_manager();
        mgr.create_user("alice", "pw", vec!["USER".to_string()])
            .await
            .unwrap();

        mgr.grant_role("alice", "DBA").await.unwrap();
        {
            let users = mgr.users.read().await;
            assert!(users
                .get("alice")
                .unwrap()
                .roles
                .contains(&"DBA".to_string()));
        }

        mgr.revoke_role("alice", "USER").await.unwrap();
        {
            let users = mgr.users.read().await;
            let user = users.get("alice").unwrap();
            assert!(!user.roles.contains(&"USER".to_string()));
            assert!(user.roles.contains(&"DBA".to_string()));
        }
    }

    #[tokio::test]
    async fn god_role_is_root_only_across_public_assignment_apis() {
        let mgr = make_manager();

        let create_error = mgr
            .create_user("alice", "pw", vec!["gOd".to_string()])
            .await
            .unwrap_err();
        assert!(matches!(create_error, GraphError::InvalidOperation(_)));
        assert!(!mgr.users.read().await.contains_key("alice"));

        mgr.create_user("alice", "pw", vec!["USER".to_string()])
            .await
            .unwrap();
        let grant_error = mgr.grant_role("alice", "god").await.unwrap_err();
        assert!(matches!(grant_error, GraphError::InvalidOperation(_)));
        assert_eq!(
            mgr.users.read().await.get("alice").unwrap().roles,
            vec!["USER".to_string()]
        );
    }

    #[tokio::test]
    async fn persisted_god_role_is_rejected_without_installing_user() {
        let mgr = make_manager();
        let user = User {
            username: "legacy-admin".to_string(),
            password_hash: byoridb_common::crypto::hash_password("pw").unwrap(),
            roles: vec!["God".to_string()],
            enabled: true,
        };

        let error = mgr.upsert_persisted_user(user).await.unwrap_err();
        assert!(matches!(error, GraphError::InvalidOperation(_)));
        assert!(!mgr.users.read().await.contains_key("legacy-admin"));
    }

    #[tokio::test]
    async fn invalid_persisted_hash_does_not_replace_cached_security_state() {
        let mgr = make_manager();
        mgr.create_user("alice", "old-password", vec!["USER".to_string()])
            .await
            .unwrap();
        let session = mgr.authenticate("alice", "old-password").await.unwrap();

        let valid_hash = byoridb_common::crypto::hash_password("replacement-password").unwrap();
        let excessive_cost_hash = valid_hash.replacen(
            "m=19456",
            &format!("m={}", MAX_PERSISTED_ARGON2_M_COST_KIB + 1),
            1,
        );
        let weak_cost_hash = valid_hash.replacen("m=19456,t=2", "m=8,t=1", 1);
        let legacy_version_hash = valid_hash.replacen("v=19", "v=16", 1);
        for invalid_hash in [
            "not-a-password-hash".to_string(),
            "$argon2id".to_string(),
            "$pbkdf2-sha256$i=1$c2FsdHNhbHQ$YWJjZA".to_string(),
            concat!(
                "$argon2id$v=19$m=19456,t=2,p=1$YWJjZA$",
                "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            )
            .to_string(),
            excessive_cost_hash,
            weak_cost_hash,
            legacy_version_hash,
        ] {
            let error = mgr
                .upsert_persisted_user(User {
                    username: "alice".to_string(),
                    password_hash: invalid_hash,
                    roles: vec!["ADMIN".to_string()],
                    enabled: true,
                })
                .await
                .unwrap_err();

            assert!(matches!(error, GraphError::InvalidOperation(_)));
            assert_eq!(
                mgr.get_session_roles(session).await,
                Some(vec!["USER".to_string()])
            );
            assert!(mgr.authenticate("alice", "old-password").await.is_ok());
        }
    }

    #[tokio::test]
    async fn test_grant_role_unknown_user_fails() {
        let mgr = make_manager();
        let err = mgr.grant_role("ghost", "USER").await.unwrap_err();
        assert!(matches!(err, GraphError::InvalidOperation(_)));
    }

    #[tokio::test]
    async fn test_sign_out_removes_session() {
        let mgr = make_manager();
        let sid = mgr.authenticate("root", TEST_PW).await.unwrap();
        mgr.sign_out(sid).await.unwrap();

        // Permission check on signed-out session should fail
        let err = mgr
            .check_permission(sid, "any_space", Permission::Read)
            .await
            .unwrap_err();
        assert!(matches!(err, GraphError::AuthFailed(_)));
    }

    #[tokio::test]
    async fn test_sign_out_unknown_session_fails() {
        let mgr = make_manager();
        let err = mgr.sign_out(9999).await.unwrap_err();
        assert!(matches!(err, GraphError::InvalidOperation(_)));
    }

    #[tokio::test]
    async fn test_session_expires() {
        let mgr = make_manager_with_ttl(Duration::from_millis(50));
        let sid = mgr.authenticate("root", TEST_PW).await.unwrap();

        tokio::time::sleep(Duration::from_millis(100)).await;

        let err = mgr
            .check_permission(sid, "any_space", Permission::Read)
            .await
            .unwrap_err();
        assert!(matches!(err, GraphError::AuthFailed(_)));
        assert!(err.to_string().to_lowercase().contains("expired"));
    }

    #[tokio::test]
    async fn session_role_access_refreshes_sliding_ttl() {
        let mgr = make_manager_with_ttl(Duration::from_millis(200));
        let sid = mgr.authenticate("root", TEST_PW).await.unwrap();

        tokio::time::sleep(Duration::from_millis(80)).await;
        assert!(mgr.get_session_roles(sid).await.is_some());
        // Total age now exceeds the original TTL, but not the refreshed TTL.
        tokio::time::sleep(Duration::from_millis(150)).await;
        assert!(mgr.get_session_roles(sid).await.is_some());
    }

    #[tokio::test]
    async fn test_cleanup_expired_sessions() {
        let mgr = make_manager_with_ttl(Duration::from_millis(50));
        let _s1 = mgr.authenticate("root", TEST_PW).await.unwrap();
        mgr.create_user("alice", "pw", vec!["USER".to_string()])
            .await
            .unwrap();
        let _s2 = mgr.authenticate("alice", "pw").await.unwrap();

        assert_eq!(mgr.sessions.read().await.len(), 2);

        tokio::time::sleep(Duration::from_millis(100)).await;

        let removed = mgr.cleanup_expired_sessions().await;
        assert_eq!(removed, 2);
        assert_eq!(mgr.sessions.read().await.len(), 0);
    }

    #[tokio::test]
    async fn test_check_permission_root_has_all() {
        let mgr = make_manager();
        let sid = mgr.authenticate("root", TEST_PW).await.unwrap();

        for p in [
            Permission::Read,
            Permission::Write,
            Permission::Create,
            Permission::Delete,
            Permission::Alter,
            Permission::Drop,
        ] {
            assert!(mgr.check_permission(sid, "any_space", p).await.unwrap());
        }
    }

    #[tokio::test]
    async fn test_check_permission_guest_is_read_only() {
        let mgr = make_manager();
        mgr.create_user("g", "pw", vec!["GUEST".to_string()])
            .await
            .unwrap();
        let sid = mgr.authenticate("g", "pw").await.unwrap();

        assert!(mgr
            .check_permission(sid, "any_space", Permission::Read)
            .await
            .unwrap());
        assert!(!mgr
            .check_permission(sid, "any_space", Permission::Write)
            .await
            .unwrap());
    }

    #[tokio::test]
    async fn test_set_user_enabled_blocks_auth() {
        let mgr = make_manager();
        mgr.create_user("alice", "pw", vec!["USER".to_string()])
            .await
            .unwrap();

        mgr.set_user_enabled("alice", false).await.unwrap();
        let err = mgr.authenticate("alice", "pw").await.unwrap_err();
        assert!(matches!(err, GraphError::AuthFailed(_)));
        assert!(err.to_string().to_lowercase().contains("disabled"));

        mgr.set_user_enabled("alice", true).await.unwrap();
        assert!(mgr.authenticate("alice", "pw").await.is_ok());
    }

    #[tokio::test]
    async fn test_cannot_disable_root() {
        let mgr = make_manager();
        let err = mgr.set_user_enabled("root", false).await.unwrap_err();
        assert!(matches!(err, GraphError::InvalidOperation(_)));
        // Root is still usable
        assert!(mgr.authenticate("root", TEST_PW).await.is_ok());
    }

    #[test]
    fn test_generate_random_password_is_unique_and_long() {
        let a = AuthManager::generate_random_password().unwrap();
        let b = AuthManager::generate_random_password().unwrap();
        assert_eq!(a.len(), 48);
        assert_eq!(b.len(), 48);
        assert_ne!(a, b);
        assert!(a.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn fallback_timing_sentinel_is_a_supported_argon2_hash() {
        assert!(AuthManager::is_supported_password_hash(
            FALLBACK_DUMMY_PASSWORD_HASH
        ));
        assert!(!AuthManager::verify_password(
            "any-presented-password",
            FALLBACK_DUMMY_PASSWORD_HASH
        ));
    }

    #[test]
    fn test_session_is_expired() {
        let now = SystemTime::now();
        let fresh = Session {
            id: 1,
            username: "u".to_string(),
            roles: vec![],
            created_at: now,
            expires_at: now + Duration::from_secs(60),
        };
        assert!(!fresh.is_expired());

        let stale = Session {
            id: 2,
            username: "u".to_string(),
            roles: vec![],
            created_at: now - Duration::from_secs(120),
            expires_at: now - Duration::from_secs(60),
        };
        assert!(stale.is_expired());
    }

    #[tokio::test]
    async fn test_brute_force_lockout() {
        let mgr = make_manager();

        // Fail MAX_FAILED_ATTEMPTS times
        for _ in 0..MAX_FAILED_ATTEMPTS {
            let err = mgr.authenticate("root", "wrong").await.unwrap_err();
            assert!(matches!(err, GraphError::AuthFailed(_)));
        }

        // Next attempt should be locked
        let err = mgr.authenticate("root", TEST_PW).await.unwrap_err();
        assert!(err.to_string().contains("locked"));
    }

    #[tokio::test]
    async fn test_brute_force_counter_resets_on_success() {
        let mgr = make_manager();

        // Fail a few times (below threshold)
        for _ in 0..MAX_FAILED_ATTEMPTS - 1 {
            let _ = mgr.authenticate("root", "wrong").await;
        }

        // Successful login clears counter
        assert!(mgr.authenticate("root", TEST_PW).await.is_ok());

        // Should be able to fail again without immediate lockout
        let err = mgr.authenticate("root", "wrong").await.unwrap_err();
        assert!(matches!(err, GraphError::AuthFailed(_)));
        assert!(!err.to_string().contains("locked"));
    }

    #[tokio::test]
    async fn persisted_auth_change_revokes_existing_sessions() {
        let mgr = make_manager();
        mgr.create_user("alice", "old-password", vec!["USER".to_string()])
            .await
            .unwrap();
        let old_session = mgr.authenticate("alice", "old-password").await.unwrap();

        let replacement = User {
            username: "alice".to_string(),
            password_hash: byoridb_common::crypto::hash_password("new-password").unwrap(),
            roles: vec!["DBA".to_string()],
            enabled: true,
        };
        assert!(mgr.upsert_persisted_user(replacement).await.unwrap());

        assert!(mgr.get_session_roles(old_session).await.is_none());
        assert!(mgr.authenticate("alice", "old-password").await.is_err());
        assert!(mgr.authenticate("alice", "new-password").await.is_ok());
    }

    #[tokio::test]
    async fn deleting_user_revokes_existing_sessions() {
        let mgr = make_manager();
        mgr.create_user("alice", "password", vec!["USER".to_string()])
            .await
            .unwrap();
        let session = mgr.authenticate("alice", "password").await.unwrap();

        mgr.delete_user("alice").await.unwrap();

        assert!(mgr.get_session_roles(session).await.is_none());
        assert!(mgr
            .check_permission(session, "default", Permission::Read)
            .await
            .is_err());
    }
}
