// Copyright (c) 2024 ByoriDB
//
// This source code is licensed under Apache 2.0 License.

//! Graph service implementation

use super::auth::AuthManager;
use super::error::{GraphError, Result};
use super::metrics::{QueryTimer, QueryType};
use super::session::SessionManager;
use byoridb_common::DataSet;
use byoridb_kvstore::KVStore;
use dashmap::DashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tokio::task::JoinHandle;
use tracing::{debug, info};

/// A query currently executing, exposed via the diagnostics endpoint so an
/// operator can see what the server is working on (and whether work continues
/// after an HTTP client timed out).
#[derive(Debug, Clone, serde::Serialize)]
pub struct RunningQuery {
    pub id: u64,
    pub session_id: i64,
    pub query_type: &'static str,
    pub query: String,
    pub space: String,
    pub started_at_ms: u64,
}

/// RAII guard: removes the query from the active registry and decrements the
/// in-flight gauge on drop, so every exit path (success, error, early return,
/// panic) cleans up.
struct ActiveQueryGuard {
    registry: Arc<DashMap<u64, RunningQuery>>,
    id: u64,
}

impl Drop for ActiveQueryGuard {
    fn drop(&mut self) {
        self.registry.remove(&self.id);
        crate::metrics::dec_inflight();
    }
}

/// Default interval for the background session-cleanup task (60 seconds).
pub const DEFAULT_SESSION_CLEANUP_INTERVAL_SECS: u64 = 60;

/// Graph service
pub struct GraphService {
    session_manager: Arc<SessionManager>,
    auth_manager: Arc<AuthManager>,
    kvstore: Arc<dyn KVStore>,
    /// Queries currently executing, keyed by a monotonic id.
    active_queries: Arc<DashMap<u64, RunningQuery>>,
    query_seq: Arc<AtomicU64>,
}

impl GraphService {
    pub fn new(kvstore: Arc<dyn KVStore>) -> Self {
        let auth_manager = Arc::new(AuthManager::new());

        GraphService {
            session_manager: Arc::new(SessionManager::new()),
            auth_manager,
            kvstore,
            active_queries: Arc::new(DashMap::new()),
            query_seq: Arc::new(AtomicU64::new(1)),
        }
    }

    /// Construct a [`GraphService`] with a caller-supplied [`AuthManager`].
    ///
    /// Embedded / in-process callers use this to inject an auth manager built
    /// with a known root password (e.g. [`AuthManager::with_config`]) so they
    /// can authenticate without depending on the `BYORIDB_ROOT_PASSWORD` env var
    /// or the random password generated by [`GraphService::new`]. The server
    /// path keeps using [`GraphService::new`] unchanged.
    pub fn with_auth(kvstore: Arc<dyn KVStore>, auth_manager: AuthManager) -> Self {
        GraphService {
            session_manager: Arc::new(SessionManager::new()),
            auth_manager: Arc::new(auth_manager),
            kvstore,
            active_queries: Arc::new(DashMap::new()),
            query_seq: Arc::new(AtomicU64::new(1)),
        }
    }

    /// Register a query in the active-query registry and bump the in-flight
    /// gauge. The returned guard removes it on drop (any exit path).
    fn register_active_query(
        &self,
        session_id: i64,
        query_type: QueryType,
        query: &str,
        space: &str,
    ) -> ActiveQueryGuard {
        let id = self.query_seq.fetch_add(1, Ordering::Relaxed);
        let started_at_ms = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_millis() as u64)
            .unwrap_or(0);
        self.active_queries.insert(
            id,
            RunningQuery {
                id,
                session_id,
                query_type: query_type.as_str(),
                query: query.to_string(),
                space: space.to_string(),
                started_at_ms,
            },
        );
        crate::metrics::inc_inflight();
        ActiveQueryGuard {
            registry: self.active_queries.clone(),
            id,
        }
    }

    /// Snapshot of queries currently executing, oldest first.
    pub fn list_active_queries(&self) -> Vec<RunningQuery> {
        let mut v: Vec<RunningQuery> = self
            .active_queries
            .iter()
            .map(|e| e.value().clone())
            .collect();
        v.sort_by_key(|q| q.started_at_ms);
        v
    }

    /// Map a write query type to its `rows_written` metric label.
    fn rows_written_op(query_type: QueryType) -> Option<&'static str> {
        match query_type {
            QueryType::Insert => Some("insert"),
            QueryType::Update => Some("update"),
            QueryType::Delete => Some("delete"),
            _ => None,
        }
    }

    /// Spawn a background task that periodically evicts expired sessions from
    /// both the [`AuthManager`] and the [`SessionManager`].
    ///
    /// The task holds [`Weak`](std::sync::Weak) references to the managers, so
    /// it exits automatically once the [`GraphService`] (and all clones of its
    /// inner [`Arc`]s) are dropped.
    pub fn spawn_session_cleanup(&self, interval: Duration) -> JoinHandle<()> {
        let auth_weak = Arc::downgrade(&self.auth_manager);
        let session_weak = Arc::downgrade(&self.session_manager);

        tokio::spawn(async move {
            let mut ticker = tokio::time::interval(interval);
            // Skip the immediate first tick.
            ticker.tick().await;

            loop {
                ticker.tick().await;

                let (auth, sessions) = match (auth_weak.upgrade(), session_weak.upgrade()) {
                    (Some(a), Some(s)) => (a, s),
                    _ => {
                        debug!("Session cleanup task exiting: service dropped");
                        break;
                    }
                };

                let auth_removed = auth.cleanup_expired_sessions().await;
                let session_removed = sessions.cleanup_expired();

                if auth_removed > 0 || session_removed > 0 {
                    debug!(
                        "Session cleanup: removed {} auth sessions, {} graph sessions",
                        auth_removed, session_removed
                    );
                }
            }
        })
    }

    /// Authenticate a user and create a session
    pub async fn authenticate(&self, username: String, password: String) -> Result<i64> {
        info!("Authentication request for user: {}", username);

        // Use AuthManager for authentication
        let session_id = self.auth_manager.authenticate(&username, &password).await?;

        // Also register in session manager for space tracking
        self.session_manager
            .create_session_with_id(session_id, username.clone())
            .await;

        debug!("Created session {} for user {}", session_id, username);

        Ok(session_id)
    }

    /// Sign out a session.
    ///
    /// `caller_session_id` is the session making the request. A session can
    /// only sign out itself unless the caller has GOD/ADMIN role.
    pub async fn sign_out(&self, caller_session_id: i64, target_session_id: i64) {
        info!(
            "Sign out request: caller={} target={}",
            caller_session_id, target_session_id
        );

        // Ownership check: caller must own the target session or be an admin.
        if caller_session_id != target_session_id {
            let is_admin = self
                .auth_manager
                .get_session_roles(caller_session_id)
                .await
                .map(|roles| roles.iter().any(|r| r == "GOD" || r == "ADMIN"))
                .unwrap_or(false);

            if !is_admin {
                tracing::warn!(
                    "sign_out denied: session {} tried to sign out session {}",
                    caller_session_id,
                    target_session_id
                );
                return;
            }
        }

        let _ = self.auth_manager.sign_out(target_session_id).await;
        self.session_manager.remove_session(target_session_id).await;
    }

    /// Execute a query statement
    pub async fn execute(&self, session_id: i64, stmt: String) -> Result<DataSet> {
        debug!("Executing query on session {}: {}", session_id, stmt);

        // Validate session and get context data
        let session = match self.session_manager.get_session(session_id).await {
            Some(s) => s,
            None => return Err(GraphError::SessionNotFound(session_id)),
        };

        let space = session
            .space
            .clone()
            .unwrap_or_else(|| "default".to_string());

        // Split on ';' to support compound statements ($var = ...; GO FROM $var ...)
        let stmts: Vec<&str> = stmt
            .split(';')
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .collect();

        if stmts.len() > 1 {
            return self.execute_compound(session_id, &session, stmts).await;
        }

        // Parse query
        let statement =
            byoridb_parser::parse(&stmt).map_err(|e| GraphError::ParseError(e.to_string()))?;

        // RBAC: check permission before execution
        let required = Self::statement_permission(&statement);
        let allowed = self
            .auth_manager
            .check_permission(session_id, &space, required)
            .await?;
        if !allowed {
            return Err(GraphError::AuthFailed(format!(
                "Permission denied: {:?} requires {:?}",
                std::mem::discriminant(&statement),
                required
            )));
        }

        // Determine query type for metrics
        let query_type = Self::get_query_type(&statement);

        // Start metrics timer (carries the query text for the slow-query log)
        let timer = QueryTimer::new(query_type, &space)
            .with_slow_threshold(1000) // 1 second threshold
            .with_query(&stmt);

        // Track as in-flight for the lifetime of this call. The guard removes
        // the entry and decrements the gauge on every exit path.
        let _active_guard = self.register_active_query(session_id, query_type, &stmt, &space);

        // Create context
        let mut context = crate::context::ExecutionContext::new(session_id);
        if let Some(space) = session.space {
            context = context.with_space(space);
        }
        // Propagate caller roles for executor-level RBAC (CREATE USER, GRANT, REVOKE)
        if let Some(roles) = self.auth_manager.get_session_roles(session_id).await {
            context = context.with_caller_roles(roles);
        }

        // Plan
        let planner =
            crate::planner::Planner::new(self.session_manager.clone(), self.kvstore.clone());
        let executor = planner.plan(statement.clone(), context.clone())?;
        // Shared flag the executor sets if it falls back to a full scan.
        let full_scan_flag = executor.full_scan_flag();

        // Execute
        let result = executor.execute().await;

        // AUTH-SYNC: on success, sync AuthManager in-memory cache
        if result.is_ok() {
            self.sync_auth_manager(&statement).await;
        }

        // Record metrics
        match &result {
            Ok(dataset) => {
                // Record write throughput: INSERT/UPDATE/DELETE return a single
                // Int row carrying the affected-row count ("Inserted"/etc).
                if let Some(op) = Self::rows_written_op(query_type) {
                    if let Some(byoridb_common::Value::Int(n)) =
                        dataset.rows.first().and_then(|r| r.first())
                    {
                        crate::metrics::record_rows_written(op, (*n).max(0) as u64);
                    }
                }
                let full_scan = full_scan_flag
                    .map(|f| f.load(std::sync::atomic::Ordering::Relaxed))
                    .unwrap_or(false);
                timer.finish(full_scan);
            }
            Err(e) => {
                timer.finish_with_error(&e.to_string());
            }
        }

        result
    }

    /// Execute a compound statement sequence, resolving `$var = <stmt>` bindings.
    ///
    /// Each statement is executed in order. If a statement has the form
    /// `$name = <query>`, the result is stored under `name` and injected into
    /// subsequent statements that reference `$name.col` in their FROM clause.
    async fn execute_compound(
        &self,
        _session_id: i64,
        session: &crate::session::Session,
        stmts: Vec<&str>,
    ) -> Result<DataSet> {
        use std::collections::HashMap;

        let mut vars: HashMap<String, byoridb_executor::ExecutorResult> = HashMap::new();
        let mut last_result = DataSet::new(vec![]);

        for raw in stmts {
            // Check for `$var = <stmt>` pattern
            let (var_name, query) = if raw.starts_with('$') {
                if let Some(eq_pos) = raw.find('=') {
                    let name = raw[1..eq_pos].trim().to_string();
                    let q = raw[eq_pos + 1..].trim();
                    (Some(name), q)
                } else {
                    (None, raw)
                }
            } else {
                (None, raw)
            };

            let statement =
                byoridb_parser::parse(query).map_err(|e| GraphError::ParseError(e.to_string()))?;

            let plan = byoridb_executor::ExecutionPlanBuilder::build(statement)
                .map_err(crate::adapter::executor_error_to_graph_error)?;

            let ctx = crate::adapter::create_executor_context(
                session.space.clone(),
                self.kvstore.clone(),
            );
            // Inject variable bindings from previous statements.
            // `ctx.vars` is now wrapped in a Mutex so the executor can
            // share the context behind an `Arc` and still mutate bindings
            // mid-query — set the contents directly here instead of
            // replacing the whole field.
            for (k, v) in &vars {
                ctx.bind_var(k.clone(), v.clone());
            }

            let executor = byoridb_executor::Executor::new(std::sync::Arc::new(ctx));
            let result = executor
                .execute(plan)
                .await
                .map_err(crate::adapter::executor_error_to_graph_error)?;

            last_result = crate::adapter::executor_result_to_dataset(result.clone());

            if let Some(name) = var_name {
                vars.insert(name, result);
            }
        }

        Ok(last_result)
    }

    /// AUTH-SYNC: after a successful user-management statement, sync the
    /// AuthManager in-memory cache so changes take effect without restart.
    async fn sync_auth_manager(&self, stmt: &byoridb_parser::Statement) {
        use byoridb_parser::ast::{CreateStatement, DropStatement};
        use byoridb_parser::Statement;

        match stmt {
            Statement::Create(CreateStatement::User(u)) => {
                let roles = u
                    .role
                    .as_deref()
                    .map(|r| vec![r.to_uppercase()])
                    .unwrap_or_default();
                if let Err(e) = self
                    .auth_manager
                    .create_user(&u.username, &u.password, roles)
                    .await
                {
                    debug!("AUTH-SYNC create_user {}: {}", u.username, e);
                }
            }
            Statement::Drop(DropStatement::User(u)) => {
                if let Err(e) = self.auth_manager.delete_user(&u.username).await {
                    debug!("AUTH-SYNC delete_user {}: {}", u.username, e);
                }
            }
            Statement::Grant(g) => {
                if let Err(e) = self.auth_manager.grant_role(&g.username, &g.role).await {
                    debug!("AUTH-SYNC grant_role {} to {}: {}", g.role, g.username, e);
                }
            }
            Statement::Revoke(r) => {
                if let Err(e) = self.auth_manager.revoke_role(&r.username, &r.role).await {
                    debug!(
                        "AUTH-SYNC revoke_role {} from {}: {}",
                        r.role, r.username, e
                    );
                }
            }
            _ => {}
        }
    }

    /// Map a statement to the minimum required Permission.
    fn statement_permission(stmt: &byoridb_parser::Statement) -> crate::auth::Permission {
        use crate::auth::Permission;
        use byoridb_parser::Statement;
        match stmt {
            // Read-only
            Statement::Show(_)
            | Statement::Describe(_)
            | Statement::Fetch(_)
            | Statement::Go(_)
            | Statement::Match(_)
            | Statement::Lookup(_)
            | Statement::Find(_) => Permission::Read,
            // Write
            Statement::Insert(_) | Statement::Update(_) | Statement::Delete(_) => Permission::Write,
            // Create / schema
            Statement::Create(_) | Statement::Alter(_) | Statement::Balance(_) => {
                Permission::Create
            }
            // Drop
            Statement::Drop(_) => Permission::Drop,
            // User management — requires GOD/ADMIN (Create covers it; GOD has all)
            Statement::Grant(_) | Statement::Revoke(_) => Permission::Create,
            // USE space — read is sufficient
            Statement::Use(_) => Permission::Read,
            Statement::Compound(_) => Permission::Read, // each sub-stmt checked individually
            Statement::Explain { .. } => Permission::Read,
        }
    }

    /// Determine query type from statement for metrics
    fn get_query_type(stmt: &byoridb_parser::Statement) -> QueryType {
        use byoridb_parser::Statement;
        match stmt {
            Statement::Show(_) => QueryType::Show,
            Statement::Describe(_) => QueryType::Show, // DESCRIBE is metadata, use Show metrics
            Statement::Use(_) => QueryType::Use,
            Statement::Create(_) => QueryType::Create,
            Statement::Alter(_) => QueryType::Create, // ALTER uses Create metrics
            Statement::Drop(_) => QueryType::Drop,
            Statement::Insert(_) => QueryType::Insert,
            Statement::Update(_) => QueryType::Update,
            Statement::Delete(_) => QueryType::Delete,
            Statement::Fetch(_) => QueryType::Fetch,
            Statement::Go(_) => QueryType::Go,
            Statement::Match(_) => QueryType::Match,
            Statement::Lookup(_) => QueryType::Lookup,
            Statement::Find(_) => QueryType::Find,
            Statement::Grant(_) => QueryType::Create, // User management uses Create metrics
            Statement::Revoke(_) => QueryType::Create,
            Statement::Balance(_) => QueryType::Show, // Admin commands use Show metrics
            // Compound queries are categorized by their dominant trailing
            // clause for metrics; default to Go since `$var = ...` chains
            // are nearly always GO traversal pipelines today.
            Statement::Compound(_) => QueryType::Go,
            Statement::Explain { .. } => QueryType::Show,
        }
    }

    /// Execute a query with parameters
    pub async fn execute_with_params(
        &self,
        session_id: i64,
        stmt: String,
        _params: std::collections::HashMap<String, String>,
    ) -> Result<DataSet> {
        self.execute(session_id, stmt).await
    }

    /// Execute a query and return JSON result
    pub async fn execute_json(&self, session_id: i64, stmt: String) -> Result<String> {
        let dataset = self.execute(session_id, stmt).await?;
        serde_json::to_string(&dataset).map_err(|e| GraphError::ExecutionError(e.to_string()))
    }
}
